apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: billing-service-nyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: billing-service-nyc
    app.kubernetes.io/part-of: test-app
  name: billing-service-nyc
  namespace: rhn-support-djodha
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: billing-service-nyc
status:
  loadBalancer: {}
