apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-java-quarkus
    app.kubernetes.io/part-of: test-app
  name: 1-java-quarkus
  namespace: rhn-support-djodha
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: 1-java-quarkus
status:
  loadBalancer: {}
